# Generated by Django 6.0.5 on 2026-08-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Zenith Bank', help_text='Bank name for payment transfers', max_length=100)),
                ('account_name', models.CharField(default='Class Sphere Ltd', help_text='Account name for payment transfers', max_length=100)),
                ('account_number', models.CharField(default='1234567890', help_text='Account number for payment transfers', max_length=20)),
                ('admin_email', models.EmailField(default='admin@classsphere.com', help_text='Email for admin notifications', max_length=254)),
                ('support_email', models.EmailField(default='support@classsphere.com', help_text='Support email', max_length=254)),
                ('support_phone', models.CharField(blank=True, help_text='Support phone number', max_length=20)),
                ('site_name', models.CharField(default='Class Sphere', help_text='Site name', max_length=100)),
                ('site_url', models.URLField(default='http://127.0.0.1:8000', help_text='Site URL for emails')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
            },
        ),
    ]
