# Generated by Django 6.0.5 on 2026-06-14 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0006_teacher_subjects_teachingassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='term',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.session'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Admission Number'),
        ),
       
    ]
