# Generated by Django 6.0.5 on 2026-06-15 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_session_options_term_session_and_more'),
        ('schools', '0006_teacher_subjects_teachingassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.session'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'admission_no'), name='unique_admission_per_school'),
        ),
    ]
