# Generated by Django 6.0.5 on 2026-05-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='school',
        ),
        migrations.AlterField(
            model_name='school',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SchoolAdmin',
        ),
    ]
